# -*- coding: utf-8 -*-
"""Amazon_alexa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9gsyoDOwUalCcpTnGbaXlFQqgE_YS75

**Data** **Preprocessing**
"""

import pandas as pd
import re

# Load the dataset
data_balanced = pd.read_csv('amazon_alexa.tsv', sep='\t')

# Extract the review column as a list
reviews = data_balanced['verified_reviews'].tolist()

# Define the text cleaning function
def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\b[a-zA-Z]\b", " ", text)
    text = re.sub(r"<[^>]*>", " ", text)
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    return text.strip()

# Clean the text in the list
cleaned_reviews = [clean_text(review) for review in reviews]

# Add the cleaned reviews as a new column to the DataFrame
data_balanced['clean_reviews'] = cleaned_reviews

# Display the updated DataFrame
print(data_balanced.head())

# Save the updated DataFrame
data_balanced.to_csv('cleaned_data.csv', index=False)
print("Cleaned data saved to 'cleaned_data.csv'")

mydata = data[['verified_reviews','feedback']]
mydata.columns = ['review','label']

mydata.head()

mydata.value_counts('label')

"""**Data Split**"""

import pandas as pd

# Assuming your DataFrame is called "df"
total_rows = len(data_balanced)
test_size = int(total_rows * 0.95)

# Randomly sample train_size rows for the training set
test_set = data_balanced.sample(test_size)

# Get the remaining rows for the test set
train_set = data_balanced.drop(test_set.index)

"""**Sentiment w/ LLM**

Setting up Gemini API
"""

!pip install -q -U google-generativeai

# Necessary packages
import pathlib
import textwrap

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

# Used to securely store your API key
from google.colab import userdata

# Or use `os.getenv('GOOGLE_API_KEY')` to fetch an environment variable.
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')

genai.configure(api_key=GOOGLE_API_KEY)

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

model = genai.GenerativeModel('gemini-pro')

# Commented out IPython magic to ensure Python compatibility.
# %%time
# response = model.generate_content("What is the meaning of life?")
# 
# to_markdown(response.text)

"""**Single API Call**


"""

test_set_sample = test_set.sample(20)

test_set_sample['pred_label'] = ''

test_set_sample

# Convert the DataFrame to JSON using the to_json() method

json_data = test_set_sample[['clean_reviews','pred_label']].to_json(orient='records')

# Print the JSON data
print(json_data)

prompt = f"""
You are an expert linguist, who is good at classifying customer review sentiments into Positive/Negative labels.
Help me classify customer reviews into: Positive(label=1), and Negative(label=0).
Customer reviews are provided between three back ticks.
In your output, only return the Json code back as output - which is provided between three backticks.
Your task is to update predicted labels under 'pred_label' in the Json code.
Don't make any changes to Json code format, please.

```
{json_data}
```
"""

print(prompt)

response = model.generate_content(prompt)

print(response.text)

import json

# Clean the data by stripping the backticks
json_data = response.text.strip("`")

# Load the cleaned data and convert to DataFrame
data = json.loads(json_data)
df_sample = pd.DataFrame(data)

df_sample

# prompt: Overwrite pred_label from 'df' into pred_label in 'train_set_sample'

test_set_sample['pred_label'] = df_sample['pred_label'].values
test_set_sample

# Plotting confusion matrix on the predictions

from sklearn.metrics import confusion_matrix

y_true = test_set_sample["rating"]
y_pred = test_set_sample["pred_label"]

confusion_matrix(y_true, y_pred)

"""OpenAI API Config"""

!pip install openai==0.28.0

import openai
from google.colab import userdata

OPENAI_API_KEY=userdata.get('openai')
openai.api_key  = OPENAI_API_KEY

def get_completion(prompt, model="gpt-3.5-turbo-1106"):

  messages = [{"role": "user", "content": prompt}]
  response = openai.ChatCompletion.create(model=model,messages=messages,temperature=0)

  return response.choices[0].message["content"]

prompt = "Why is the sky blue?"

chatgpt_response = get_completion(prompt)

chatgpt_response

"""Batching API Calls (Single Shot)"""

test_set.shape

test_set_total = test_set.sample(100)

test_set_total['rating'] = ''

test_set_total

batches = []
batch_size = 50

for i in range(0, len(test_set_total), batch_size):
  batches.append(test_set_total[i : i + batch_size])  # Append batches instead of assigning

import time

def gpt_completion_function(batch,current_batch,total_batch,model="gpt-3.5-turbo-1106"):
  """Function works in three steps:
  # Step-1: Convert the DataFrame to JSON using the to_json() method.
  # Step-2: Preparing the Gemini Prompt
  # Step-3: Calling GPT API
  """

  print(f"Now processing batch#: {current_batch+1} of {total_batch}")

  json_data = batch[['clean_reviews','pred_label']].to_json(orient='records')

  prompt = f"""You are an expert linguist, who is good at classifying customer review sentiments into Positive/Negative labels.
  Help me classify customer reviews into: Positive(label=1), and Negative(label=0).
  Customer reviews are provided between three backticks below.
  In your output, only return the Json code back as output - which is provided between three backticks.
  Your task is to update predicted labels under 'pred_label' in the Json code.
  Don't make any changes to Json code format, please.
  Error handling instruction: In case a Customer Review violates API policy, please assign it default sentiment as Negative (label=0).

  ```
  {json_data}
  ```
  """

  print(prompt)

  messages = [{"role": "user", "content": prompt}]
  response = openai.ChatCompletion.create(model=model,messages=messages,temperature=0)
  time.sleep(5)
  return response.choices[0].message["content"]

responses = []

for i, batch in enumerate(batches):
    print(f"Now processing batch#: {i + 1} of {len(batches)}")

    # Construct the prompt for the current batch
    prompt = f"""
    You are an expert linguist, who is good at classifying customer review sentiments into Positive/Negative labels.
    Help me classify customer reviews into: Positive(label=1), and Negative(label=0).
    Customer reviews are provided between three backticks below.
    In your output, only return the Json code back as output - which is provided between three backticks.
    Your task is to update predicted labels under 'pred_label' in the Json code.
    Don't make any changes to Json code format, please.
    Error handling instruction: In case a Customer Review violates API policy, please assign it default sentiment as Negative (label=0).

    ```
    {batch}
    ```
    """
    try:
        # Call the GPT function
        response = gpt_completion_function(prompt, i, len(batches))
        responses.append(response)
    except Exception as e:
        print(f"Error while processing batch {i + 1}: {e}")
        # Append a default response or handle the batch failure as needed
        responses.append({"error": f"Failed to process batch {i + 1}"})

# Print all responses after processing
for idx, res in enumerate(responses):
    print(f"Batch {idx + 1} Response:\n", res)

import json

# JSON string containing the reviews
json_data = '''[
    {"clean_reviews":"love it don know what took me so long to get one and don know why didn get two on amazon prime day","pred_label":""},
    {"clean_reviews":"we really love our echo dot we can get questions answered right away and play any music we can think of","pred_label":""},
    {"clean_reviews":"like it alot connected it so can play my pandora and asked about the weather time every morning got rid of my old fashioned digitol clock because can have my music play unlimited on this going to ask it about vacations and few other things once get more comfortable with it definitely worth the money","pred_label":""},
    {"clean_reviews":"like how it will connect to bluetooth without an adapter like the google only reason for 4 stars is volume level without external speaker easy to use","pred_label":""}
]'''

# Convert JSON string to Python list
reviews = json.loads(json_data)

# Dummy function to predict sentiment (replace this with your actual API or ML model)
def predict_sentiment(review_text):
    if "love" in review_text or "great" in review_text or "enjoying" in review_text:
        return 1  # Positive
    else:
        return 0  # Negative

# Process each review and update the 'pred_label'
for review in reviews:
    review_text = review.get("clean_reviews", "")
    # If review is empty or violates policy, default to Negative
    if not review_text.strip():
        review["pred_label"] = 0
    else:
        review["pred_label"] = predict_sentiment(review_text)

# Convert back to JSON
updated_json = json.dumps(reviews, indent=4)
print(updated_json)

# Optionally save to a file in Colab
with open("classified_reviews.json", "w") as f:
    f.write(updated_json)

batch_count = len(batches)
responses = []

for i in range(0,len(batches)):
  responses.append(gpt_completion_function(batches[i],i,batch_count))

import json

df_total = pd.DataFrame()  # Initialize an empty DataFrame

for response in responses:
  # Clean the data by stripping the backticks
  json_data = response.strip("`")

  # Load the cleaned data and convert to DataFrame
  data = json.loads(json_data)
  df_temp = pd.DataFrame(data)

  # Append the DataFrame to the final DataFrame
  df_total = df_total.append(df_temp, ignore_index=True)

print(df_total)  # Display the final DataFrame

# prompt: Overwrite pred_label from 'df' into pred_label in 'train_set_sample'

test_set_total['pred_label'] = df_total['pred_label'].values
test_set_total

# Plotting confusion matrix on the predictions

from sklearn.metrics import confusion_matrix, accuracy_score

y_true = test_set_total["label"]
y_pred = test_set_total["pred_label"]

print(confusion_matrix(y_true, y_pred))
print(f"\nAccuracy: {accuracy_score(y_true, y_pred)}")

"""**Batching API Calls: Gemini API**"""

test_set.shape

test_set_total = test_set.sample(100)

test_set_total['rating'] = ''

test_set_total

batches = []
batch_size = 25

for i in range(0, len(test_set_total), batch_size):
  batches.append(test_set_total[i : i + batch_size])  # Append batches instead of assigning



import time

def gemini_completion_function(batch,current_batch,total_batch):
  """Function works in three steps:
  # Step-1: Convert the DataFrame to JSON using the to_json() method.
  # Step-2: Preparing the Gemini Prompt
  # Step-3: Calling Gemini API
  """

  print(f"Now processing batch#: {current_batch+1} of {total_batch}")

  json_data = batch[['clean_reviews','rating']].to_json(orient='records')

  prompt = f"""You are an expert linguist, who is good at classifying customer review sentiments into Positive/Negative labels.
  Help me classify customer reviews into: Positive(label=1), and Negative(label=0).
  Customer reviews are provided between three backticks below.
  In your output, only return the Json code back as output - which is provided between three backticks.
  Your task is to update predicted labels under 'pred_label' in the Json code.
  Don't make any changes to Json code format, please.
  Error handling instruction: In case a Customer Review violates API policy, please assign it default sentiment as Negative (label=0).

  ```
  {json_data}
  ```
  """

  print(prompt)
  response = model.generate_content(prompt)
  time.sleep(5)

  return response

batch_count = len(batches)
responses = []

for i in range(0,len(batches)):
  responses.append(gemini_completion_function(batches[i],i,batch_count))

import json
import pandas as pd  # Ensure pandas is imported

df_total = pd.DataFrame()  # Initialize an empty DataFrame

for response in responses:
    # Clean the data by stripping the backticks
    json_data = response.text.strip("`")

    # Load the cleaned data and convert it to a DataFrame
    data = json.loads(json_data)
    df_temp = pd.DataFrame(data)

    # Concatenate the DataFrame to the final DataFrame
    df_total = pd.concat([df_total, df_temp], ignore_index=True)

print(df_total)  # Display the final DataFrame

# prompt: Overwrite pred_label from 'df' into pred_label in 'train_set_sample'

test_set_total['rating'] = df_total['rating'].values
test_set_total

# Plotting confusion matrix on the predictions

from sklearn.metrics import confusion_matrix

y_true = test_set_total["rating"]
y_pred = test_set_total["clean_reviews"]

confusion_matrix(y_true, y_pred)